### ISSUE TITLE
Can you check what is wrong?

### ISSUE THREAD

**Issue by bryant-the-coder** [kvrohit/substrata.nvim#13]
@kvrohit https://github.com/bryant-the-coder/astron.nvim

this is my newly made colorscheme. I cant seem to get it working even following substrata.

error i got
![image](https://user-images.githubusercontent.com/92417638/153716661-78782fcf-3d8f-48b3-9097-45cc0cf5e028.png)

**Comment by bryant-the-coder** [comment]
i cant seem to find what is wrong ಥ‿ಥ

**Comment by kvrohit** [comment]
@bryant-the-coder Sorry, couldn't get to this earlier. Were you able to figure out the issue?

**Comment by bryant-the-coder** [comment]
yes @kvrohit , solved it. you can try the colorscheme and tell me what i can patch :)
