### ISSUE TITLE
Text Color change on cursor hover

### ISSUE THREAD

**Issue by 0xhealer** [kvrohit/substrata.nvim#15]
Hello,
First of all great theme. I have been using it for VScode as well as my gnome-terminal. Really love the colors :).
While changing theme for neovim, I stumbled upon the issue with the text color.It get completely darkened when the cursor is over that text. I tried it with other colorscheme and did not have any issue regarding this.

![proper](https://user-images.githubusercontent.com/76742567/193316396-738440ae-a202-4a48-9030-937d58c13f18.png)
Below is the issue with the text color, here the function keyword has been darkened
![issue](https://user-images.githubusercontent.com/76742567/193316498-5bb83f7c-bd8d-4c91-ad62-8a95e9c6e4ac.png)
Do check it out :)

**Comment by kvrohit** [comment]
Can I know which terminal you are using and have you enabled `cursorline`? Let me know if you can reproduce this on different terminals.

**Comment by 0xhealer** [comment]
I'm using the default Gnome Terminal, my cursorline is disabled. Will check on alacritty and get back to you :)

**Comment by 0xhealer** [comment]
It happens the after some time when I go to insert mode in both the gnome and alacritty. I keep shifting from insert mode to normal mode and after 3-4 times, this issue starts.

**Comment by kvrohit** [comment]
Hmm, that's strange, will try and reproduce based on your description and
get back.

**Comment by jeffreylouden** [comment]
I'm experiencing a similar issue in Kitty and on top of AstroNvim. I have `CursorLine` enabled, which prevents the text from disappearing completely, but the foreground text is being set to the background color when under cursor.

![Screenshot from 2022-10-06 15-08-20](https://user-images.githubusercontent.com/755858/194398631-2c46cce0-698e-479a-b698-1f0c20107951.png)
