### ISSUE TITLE
Making colorscheme

### ISSUE THREAD

**Issue by bryant-the-coder** [kvrohit/substrata.nvim#8]
How do you create this colorscheme?

**Comment by kvrohit** [comment]
Borrowed the colors from `vim-substrata` theme and code from `neon` and `tokyonight` color schemes 😁

**Comment by bryant-the-coder** [comment]
oh ok thx... is it possible to steal the layout of the file?

**Comment by bryant-the-coder** [comment]
i mean use. use the layout

**Comment by kvrohit** [comment]
Sure. In fact you can clone this project, change the colors in `colors.lua` and viola! you have a new theme. Of course change the name to something else 😉

**Comment by bryant-the-coder** [comment]
thx

**Comment by bryant-the-coder** [comment]
happy new year btw

**Comment by kvrohit** [comment]
> happy new year btw

Happy new year!

**Comment by bryant-the-coder** [comment]
Oh ya where u reference all of this theme? i cant seem to find any online sources that teaches all this

**Comment by kvrohit** [comment]
Reverse engineered from other theme implementations mostly. I don't think there is any guide that teaches you how to do this, but it might be worth searching on the web. Also ThePrimeagen & TJDeVries have videos (on youtube) on making plugins in general that might help.

**Comment by bryant-the-coder** [comment]
thx again :))
